### ISSUE TITLE
Migrate project to Firestore

### ISSUE THREAD

**Issue by malliaridis** [malliaridis/Qsol#2]
## Task Background
To be able to simplify specific procedures and to improve performance, some database changes are necessary. Together with these changes a migration to firestore was proposed and accepted. Consequently the whole project needs to be migrated to the firestore (initially realtime database). 

## Task that have to be done
* [x] Replace any realtime database query with a firestore query
* [x] Simplify simultaneously the project by replacing duplicate activities and layouts 
* [x] Check if everything works as before (or as wanted)

**Comment by malliaridis** [comment]
This issue does not cover the Quick Search section, since this is mentioned in the issue #1.  This allows an earlier merging of the firestore migration changes.

**Comment by malliaridis** [comment]
Closed by #3
